blank_issues_enabled: false
contact_links:
  - name: HangarMC Discord
    url: https://discord.gg/zvrAEbvJ4a
    about: If you are having smaller issues or have a general question, come ask us on our Discord server
